[package]
name = "guessing-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies] #header
rand="0.8.5" #semantic versioning is shorthand for ^0.8.5 at least 0.8.5 but below 0.9.0